kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1 
metadata:
  name: ram-role-binding
  namespace: dev 
subjects:
- kind: User 
  name: ram 
  apiGroup: rbac.authorization.k8s.io 
roleRef:
  kind: Role
  name: ram-role 
  apiGroup: rbac.authorization.k8s.io
